---
- include_vars: roles/hadoop_common/vars/main.yml
  tags:
    - install

- name: Put Mirai data from /sparkapps/src/test/resources to HDFS
  shell: >
    su - {{ hdfsuser }} -c "hadoop fs -put -f /{{ mirai_container }}/en-ja-int-train.snt /test/data/";
  # ignore errors if already exists
  ignore_errors: true
  tags:
    - configure

# The following are commented out because they could be useful later    

#- name: Unpack training stuff to /root
#  unarchive: copy=no src="/{{ ampcamp_container }}/training.tar.gz" dest=/root/
#  tags:
#    - install

#- name: Create some symlinks for convenience
#  file: src=/root/training/{{ item }} dest=/root/{{ item }} state=link
#  with_items:
#    - java-app-template
#    - machine-learning
#    - scala-app-template
#    - streaming
#  tags:
#    - install

#- name: Create /root/spark-ec2 directory to store configs required by AMPCamp examples
#  file: path=/root/spark-ec2 state=directory
#  tags:
#    - install

- include_vars: roles/spark_standalone/vars/main.yml
  tags:
    - configure

#- name: Create config files required by AMPCamp examples MLlib and GraphX
#  template: src={{ item }}.j2 dest=/root/spark-ec2/{{ item }}
#  with_items:
#    - cluster-url
#    - masters
#  tags:
#    - configure

